# .goreleaser.yaml
version: 2
project_name: gen

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w -X github.com/anibaldeboni/gen/cmd.Version={{.Version}}

  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags:
      - -s -w -X github.com/anibaldeboni/gen/cmd.Version={{.Version}}

  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w -X github.com/anibaldeboni/gen/cmd.Version={{.Version}}

archives:
  - id: darwin
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    builds:
      - darwin
    wrap_in_directory: false
    format_overrides:
      - goos: darwin
        formats: [zip]

  - id: linux
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    builds:
      - linux
    wrap_in_directory: false

  - id: windows
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    builds:
      - windows
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
